// Code generated by https://github.com/lu4p/embed-encrypt; DO NOT EDIT.

package main

import (
	"embed"
	"github.com/lu4p/embed-encrypt/encryptedfs"
)

//go:embed .fskey
var key []byte

func init() {
	//go:embed "hello.txt.enc"
	var enc string
	hello = encryptedfs.DecString(enc, key)
}
func init() {
	//go:embed "gopher.png.enc"
	var enc []byte
	gopher = encryptedfs.DecByte(enc, key)
}
func init() {
	//go:embed "gopher.png.enc" "hello.txt.enc" "another.txt.enc" "with spaces .txt.enc"
	var enc embed.FS
	multiplefiles = encryptedfs.InitFS(enc, key)
}
func init() {
	//go:embed "another.txt.enc" "hello.txt.enc" "with spaces .txt.enc"
	var enc embed.FS
	glob = encryptedfs.InitFS(enc, key)
}
