// Code generated by https://github.com/abakum/embed-encrypt; DO NOT EDIT.

package main

import (
	"embed"
	"github.com/abakum/embed-encrypt/encryptedfs"
	"github.com/abakum/embed-encrypt/example/internal/tool"
)

var key []byte

func init() {
	key = tool.Priv()
}

//go:embed "hello.txt.enc"
var enc1 string

func init() {
	hello = encryptedfs.DecString(enc1, key)
}

//go:embed "gopher.png.enc"
var enc2 []byte

func init() {
	gopher = encryptedfs.DecByte(enc2, key)
}

//go:embed "hello.txt.enc" "another.txt.enc" "with spaces .txt.enc"
var enc3 embed.FS

func init() {
	multiplefiles = encryptedfs.InitFS(enc3, key)
}

//go:embed "another.txt.enc" "hello.txt.enc" "with spaces .txt.enc"
var enc4 embed.FS

func init() {
	glob = encryptedfs.InitFS(enc4, key)
}
